"""Add travel_idea_group and travel_idea_group_member tables

Revision ID: e1b007ed5bae
Revises: 9ce108863dbf
Create Date: 2025-11-19 21:45:47.298969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1b007ed5bae'
down_revision: Union[str, Sequence[str], None] = '9ce108863dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_idea_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('owned_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owned_by_id'], ['user_account.id'], name=op.f('fk_travel_idea_group_owned_by_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_travel_idea_group'))
    )
    op.create_table('travel_idea_group_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_account_id', sa.Integer(), nullable=False),
    sa.Column('travel_idea_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['travel_idea_group_id'], ['travel_idea_group.id'], name=op.f('fk_travel_idea_group_member_travel_idea_group_id_travel_idea_group')),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.id'], name=op.f('fk_travel_idea_group_member_user_account_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_travel_idea_group_member'))
    )
    op.add_column('travel_idea', sa.Column('travel_idea_group_id', sa.Integer(), nullable=False))
    op.alter_column('travel_idea', 'name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_foreign_key(op.f('fk_travel_idea_travel_idea_group_id_travel_idea_group'), 'travel_idea', 'travel_idea_group', ['travel_idea_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_travel_idea_travel_idea_group_id_travel_idea_group'), 'travel_idea', type_='foreignkey')
    op.alter_column('travel_idea', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('travel_idea', 'travel_idea_group_id')
    op.drop_table('travel_idea_group_member')
    op.drop_table('travel_idea_group')
    # ### end Alembic commands ###
